[application]
name = "Toolbox"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[desktop]
width = 600
height = 400


[bundle]
identifier = "com.caofengyi.toolbox"
publisher = "caofengyi"
icon = ["./icons/toolbox.icns"]


[platform.macos]
bundle = true
dmg = true
